sudo: false
language: node_js

cache:
  - node_modules

matrix:
  include:
    - name: "Lint"
      node_js: "10"
      script: make lint

    - name: "Test on Node.js v8.x"
      node_js: "8"
      script: make test
    - name: "Test on Node.js v10.x"
      node_js: "10"
      script: make test
