language: node_js
node_js:
- "8"
cache: yarn

# We don't have a 'test' script in package.json. We use make instead.
script:
- make test

# A working Git+SSH setup is required by the deploy task. Configure Git and SSH
# so that it can push to the GitHub repository.
# before_deploy:
# - git config --global user.name "Travis CI"
# - git config --global user.email "travis-ci@interactivethings.com"
# - eval `ssh-agent -s`
# - openssl aes-256-cbc -K $encrypted_67b727d8d9f9_key -iv $encrypted_67b727d8d9f9_iv
#   -in deploy-key.enc -d | ssh-add -
deploy:
  provider: script
  script: make publish
  on:
    tags: true
# env:
#   global:
#     secure: M295ObhEGAxLG9syGV8o1nErAGvSg49TAEspNxuv4ur8V0qu1VeS6Pol4DEVyySdnejByEBnAhTJDuWLGR5rJcnU2DA0GWB8fusGfLJAb1wztB2TAaqacPqfDTTgRsFhUv3vW+eAMosRtuAIi+CqVJSYBkl0twUfBrUxkjemcLM=
